"""Mypy stub for Hermes' ``agent.memory_provider`` (Hermes runtime only).

Tabularius subclasses ``MemoryProvider`` when running inside Hermes. The
package must also import cleanly standalone (unit tests, packaging), so the
real import is guarded; this stub gives mypy the exact ABC surface.
"""

from typing import Any, Dict, List, Optional

class MemoryProvider:
    @property
    def name(self) -> str: ...
    def is_available(self) -> bool: ...
    def initialize(self, session_id: str, **kwargs: Any) -> None: ...
    def system_prompt_block(self) -> str: ...
    def prefetch(self, query: str, *, session_id: str = "") -> str: ...
    def queue_prefetch(self, query: str, *, session_id: str = "") -> None: ...
    def sync_turn(
        self,
        user_content: str,
        assistant_content: str,
        *,
        session_id: str = "",
        messages: Optional[List[Dict[str, Any]]] = None,
    ) -> None: ...
    def get_tool_schemas(self) -> List[Dict[str, Any]]: ...
    def handle_tool_call(self, tool_name: str, args: Dict[str, Any], **kwargs: Any) -> str: ...
    def on_session_end(self, messages: List[Dict[str, Any]]) -> None: ...
    def on_session_switch(self, new_session_id: str, **kwargs: Any) -> None: ...
    def on_pre_compress(self, messages: List[Dict[str, Any]]) -> str: ...
    def on_memory_write(
        self,
        action: str,
        target: str,
        content: str,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> None: ...
    def on_delegation(self, task: str, result: str, **kwargs: Any) -> None: ...
    def get_config_schema(self) -> List[Dict[str, Any]]: ...
    def save_config(self, values: Dict[str, Any], hermes_home: str) -> None: ...
    def shutdown(self) -> None: ...
    def backup_paths(self) -> List[str]: ...
