"""Tests for agents/index.py — index agent + related blocks (issue #9)."""

from __future__ import annotations

import json

import pytest
from fakes import _FakeMessage, _FakeResponse, _ScriptedClient, index_output_json

from tabularius.agents import index
from tabularius.schemas import IndexAgentOutput, ReaderAgentOutput


@pytest.fixture
def docs(memory_root) -> None:
    (memory_root / "a.md").write_text("# A", encoding="utf-8")
    (memory_root / "b.md").write_text("# B", encoding="utf-8")
    (memory_root / "c.md").write_text("# C", encoding="utf-8")


def _readers() -> dict[str, ReaderAgentOutput]:
    return {
        "a.md": ReaderAgentOutput(
            path="a.md", summary="About A", key_topics=["a"], category_hint="a"
        ),
        "b.md": ReaderAgentOutput(
            path="b.md", summary="About B", key_topics=["b"], category_hint="b"
        ),
        "c.md": ReaderAgentOutput(
            path="c.md", summary="About C", key_topics=["c"], category_hint="c"
        ),
    }


def _stub_readers(monkeypatch: pytest.MonkeyPatch) -> None:
    def fake_run_reader(path: str, *, client=None) -> ReaderAgentOutput:
        return _readers()[path]

    monkeypatch.setattr("tabularius.agents.index.run_reader", fake_run_reader)


class TestIndexAgent:
    def test_generates_index_and_related_blocks(self, memory_root, docs, monkeypatch) -> None:
        _stub_readers(monkeypatch)
        client = _ScriptedClient([_FakeResponse(_FakeMessage(index_output_json()))])
        out = index.run_index_agent(client=client)  # type: ignore[arg-type]
        assert isinstance(out, IndexAgentOutput)
        assert out.stats["entries"] == 3

        index_content = (memory_root / "INDEX.md").read_text(encoding="utf-8")
        assert "## Categories" in index_content
        assert "- `a.md` — A desc" in index_content

        a_content = (memory_root / "a.md").read_text(encoding="utf-8")
        assert "# A" in a_content  # original content preserved
        assert "## Related" in a_content
        assert "- b.md" in a_content
        assert "- c.md" in a_content

    def test_missing_entries_filled_from_readers(self, memory_root, docs, monkeypatch) -> None:
        _stub_readers(monkeypatch)
        partial = json.dumps(
            {
                "index_entries": [{"path": "a.md", "description": "A desc", "related": ["b.md"]}],
                "stats": {},
            }
        )
        client = _ScriptedClient([_FakeResponse(_FakeMessage(partial))])
        out = index.run_index_agent(client=client)  # type: ignore[arg-type]
        index_content = (memory_root / "INDEX.md").read_text(encoding="utf-8")
        assert "- `a.md` — A desc" in index_content
        assert "- `b.md` — About B" in index_content  # filled from reader summary
        assert "- `c.md` — About C" in index_content
        assert out.stats["entries"] == 3

    def test_reindex_is_idempotent(self, memory_root, docs, monkeypatch) -> None:
        _stub_readers(monkeypatch)
        for _ in range(2):
            client = _ScriptedClient([_FakeResponse(_FakeMessage(index_output_json()))])
            index.run_index_agent(client=client)  # type: ignore[arg-type]

        assert (memory_root / "INDEX.md").read_text(encoding="utf-8") == (
            "# Memory Index\n"
            "\n"
            "<!-- auto-generated by tabularius; edit via reindex -->\n"
            "\n"
            "## Categories\n"
            "- `a.md` — A desc\n"
            "- `b.md` — B desc\n"
            "- `c.md` — C desc\n"
        )
        assert (memory_root / "a.md").read_text(encoding="utf-8") == (
            "# A\n\n## Related\n- b.md\n- c.md\n"
        )
